### ISSUE TITLE
Review CPU types for recommending AVX2 and Intel builds of TensorFlow

### ISSUE THREAD

**Issue by fridex** [thoth-station/adviser#1022]
**Describe the request**

Let's review CPUs we use for recommending AVX2 builds of TensorFlow. See https://github.com/thoth-station/adviser/pull/1020 for more info.

We should conform to CPU docs and see which CPUs offer AVX2 support given the CPU family/model.

**Comment by fridex** [comment]
Also recommended Intel builds should be reviewed. See https://github.com/thoth-station/adviser/pull/1093

**Comment by harshad16** [comment]
I tried to verify each cpu processer arch we listed with the cpu family, model and also if they include avx2 instruction set extension.
# Cascade Lake ,(0x6, 0x5) 
https://en.wikichip.org/wiki/intel/microarchitectures/cascade_lake
#Cannon Lake,(0x6, 0x6)
https://en.wikichip.org/wiki/intel/microarchitectures/cannon_lake
# Broadwell,(0x6, 0x6) 
https://en.wikichip.org/wiki/intel/cores/broadwell_de
# Ice Lake,(0x6, 0xA),(0x6, 0xC),(0x6, 0xD),(0x6, 0xE)
https://en.wikichip.org/wiki/intel/cores/ice_lake_u
https://en.wikichip.org/wiki/intel/cores/ice_lake_y
#Tiger Lake, (0x6, 0xC)
https://en.wikipedia.org/wiki/Tiger_Lake_(microprocessor)
https://en.wikichip.org/wiki/intel/microarchitectures/tiger_lake
#Kaby Lake, (0x6, 0xE)
https://en.wikichip.org/wiki/intel/microarchitectures/kaby_lake
#Coffee Lake,(0x6, 0xE)
https://en.wikichip.org/wiki/intel/microarchitectures/coffee_lake
#Comet Lake,(0x6, 0xE)
https://en.wikichip.org/wiki/intel/microarchitectures/comet_lake
# Skylake, (0x6, 0xE)
https://en.wikichip.org/wiki/intel/microarchitectures/skylake_(client)
# Haswell, (0x6, 0xF)
https://en.wikichip.org/wiki/intel/microarchitectures/haswell_(client)
also seems to be correct.
apart from these , one more processer arch whiskey_lake (0x6, 0xE) https://en.wikichip.org/wiki/intel/microarchitectures/whiskey_lake also contains avx2 extension.

**Comment by harshad16** [comment]
There is a typo in naming of one of microarch https://github.com/thoth-station/adviser/blob/45df9d2f25e5536d44b6b9b8ca363ce43c94911b/thoth/adviser/steps/tensorflow_avx2.py#L67
it is to be kaby lake.

**Comment by fridex** [comment]
> Also seems to be correct.
> apart from these , one more processer arch:
> 
> * whiskey_lake (0x6, 0xE) https://en.wikichip.org/wiki/intel/microarchitectures/whiskey_lake also contains avx2 extension.

Awesome! :clap: :+1: 

According to sources, we should be already producing the right recommendations. We should add it to the listing in comment then.

**Comment by fridex** [comment]
@harshad16 do you mind opening a PR and close this issue with your work done? :+1:
