### ISSUE TITLE
Define recommendation types we want to provide [3pt]

### ISSUE THREAD

**Issue by goern** [thoth-station/adviser#1053]
As a Thoth Product Owner,
I want to present a document to the user,
so that the user understands what recommendation types are available,
and so that we can show pros and cons of rec_types

**Comment by pacospace** [comment]
https://docs.google.com/document/d/1K6g80xR7Swmk6-1Ap6CpGKQtrvXMd7ESs6O7_IEJ7KU/edit#

**Comment by fridex** [comment]
Following the current recommendation types we have:

https://github.com/thoth-station/adviser/blob/33b7fe25767626d57a5590e0c033ca6216ba16a0/thoth/adviser/enums.py#L40-L45

* STABLE
* LATEST
* TESTING

We could also include:

* PERFORMANT
* SECURE

As we will add more pipeline units, I would suggest creating documentation directly in pipeline units so it does not go out of sync with the actual implementation.

The documentation would be automatically rendered and updated in the docs. A link to boot pipeline units documentation:

https://thoth-station.ninja/docs/developers/adviser/thoth.adviser.boots.html

WDYT?

**Comment by pacospace** [comment]
> Following the current recommendation types we have:
> 
> https://github.com/thoth-station/adviser/blob/33b7fe25767626d57a5590e0c033ca6216ba16a0/thoth/adviser/enums.py#L40-L45
> 
> * STABLE
> * LATEST
> * TESTING
> 
> We could also include:
> 
> * PERFORMANT
> * SECURE
> 
> As we will add more pipeline units, I would suggest creating documentation directly in pipeline units so it does not go out of sync with the actual implementation.
> 
> The documentation would be automatically rendered and updated in the docs. A link to boot pipeline units documentation:
> 
> https://thoth-station.ninja/docs/developers/adviser/thoth.adviser.boots.html
> 
> WDYT?

Sounds great to me :)

**Comment by goern** [comment]
> SECURE

seems to be a very absolute statement to me, I guess the sentiment is "this software stack should be optimized towards security" ?

What about "performance" and "security" ?

**Comment by fridex** [comment]
> > SECURE
> 
> seems to be a very absolute statement to me, I guess the sentiment is "this software stack should be optimized towards security" ?
> 
> What about "performance" and "security" ?

Adjusted, PTAL.
