### ISSUE TITLE
public list of recommendations [5pt]

### ISSUE THREAD

**Issue by goern** [thoth-station/adviser#1126]
As a Developer,
I want to receive advises including links to a public list of recommendations,
so that I can read more information
and so that I can click on it in Qeb-Hwt check details

**Comment by goern** [comment]
I think each justification should get a unique id, at least the generalized form of each justification. This way we reference it in an advise. 

A similar system is used by other tools too (maybe we should first gather a list of examples of other tools).

**Comment by fridex** [comment]
Here one can find a list of recommendations we provide:

https://thoth-station.ninja/justifications

The recommendation listing is automatically generated on each push to https://github.com/thoth-station/thoth-station.github.io repo - all these "justification documents" live in `_j` directory.

See also https://github.com/thoth-station/thoth-station.github.io/pull/128 for recommendation types listing. I think we can close this issue.
