### ISSUE TITLE
Run pytest in Zuul

### ISSUE THREAD

**Issue by fridex** [thoth-station/adviser#114]
We have a testsuite that runs unit tests. We should run this testsuite in CI.

Locally I run it as:
```
PYTHONPATH=. THOTH_LOG_ADVISER_PIPFILE="DEBUG" python3 -m pytest tests/ -vvvvv
```

**Comment by goern** [comment]
as we have https://github.com/thoth-station/zuul-test-jobs/blob/master/roles/thoth-pytest/tasks/main.yaml executed via https://github.com/thoth-station/adviser/blob/master/.zuul.yaml#L5 I think this implemented.

@fridex syn?

**Comment by fridex** [comment]
Ack.
