### ISSUE TITLE
Adviser should expose transitive dependencies missing in report so that solver can be scheduled faster

### ISSUE THREAD

**Issue by pacospace** [thoth-station/adviser#1164]
**Is your feature request related to a problem? Please describe.**
Currently when adviser fails due to missing transitive dependencies we do not find the name of the packages in the report. It would be nice to find them as for unresolved packages of direct dependencies. In this way we can speed the scheduling of solvers for user software stacks

**Describe the solution you'd like**
Include transitive dependencies in unresolved packages in adviser report.

**Describe alternatives you've considered**

**Additional context**

**Comment by fridex** [comment]
I'm really not sure if we want to do this - direct dependencies have slightly different use case.

The way system is designed: pre-compute data for users in advance based on the packages users use (direct dependencies). This means the system will schedule transitive dependencies on its own in the background. Scheduling transitive dependencies this way can introduce unnesessary complexity and basically zero value add (these solvers will be scheduled by graph-refresh).

**Comment by pacospace** [comment]
> I'm really not sure if we want to do this - direct dependencies have slightly different use case.
> 
> The way system is designed: pre-compute data for users in advance based on the packages users use (direct dependencies). This means the system will schedule transitive dependencies on its own in the background. Scheduling transitive dependencies this way can introduce unnesessary complexity and basically zero value add (these solvers will be scheduled by graph-refresh).

This is related to with https://github.com/thoth-station/investigator/issues/63 I think.
If we solved a missing dependency might be that adviser will still fail due to missing transitive dependencies.

Basically adviser will be re run continuously until transitive dependencies will be solved as well, even though direct one are all solved. But there is no direct control on it in this case, we need to wait for graph-refresh that will randomly pick packages and if the system is fast enough we would have everything solved to have a successful adviser run.

**Comment by pacospace** [comment]
As discussed in the call, this situation it's high unlikely so we can close this issue.
