### ISSUE TITLE
test repo for SI demo

### ISSUE THREAD

**Issue by goern** [thoth-station/adviser#1183]
**Is your feature request related to a problem? Please describe.**
As a Developer,
I want to use `thamos advise`
so that I receive Security Indicator related advise

**Describe the solution you'd like**
We should have a repo that has pinned some old version of a python module, after running thamos advise, we should see why we recommend a newer version of the module: the SI rating was above a certain threshold 

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

/kind feature
/priority important-soon

**Comment by pacospace** [comment]
As suggested yesterday with @fridex, we have already https://github.com/thoth-station/cli-examples for examples, no need of new repo.
