### ISSUE TITLE
create demo for "adviser now supports advises specific for manifest changes" [3pt]

### ISSUE THREAD

**Issue by goern** [thoth-station/adviser#1228]
As a Developer
I want to use `thamos advise`
so that it recommends what I should change in a DeploymentConfig

/priority critical-urgent
/assign @bissenbay @fridex
/label thoth/group-programming

**Comment by fridex** [comment]
https://www.youtube.com/watch?v=RNv8jQxEBP8

**Comment by bissenbay** [comment]
> https://www.youtube.com/watch?v=RNv8jQxEBP8

thanks @fridex
