### ISSUE TITLE
Issue with adviser v0.17.0 in stage environment

### ISSUE THREAD

**Issue by fridex** [thoth-station/adviser#1230]
**Describe the bug**

I see the following error in stage environment with the current setup:

```
2020-09-17 06:58:28,404   1 INFO     thoth.adviser:183: Version: 0.17.0
2020-09-17 06:58:28,569   1 CRITICAL root:102: Traceback (most recent call last):
  File "thoth-adviser", line 762, in <module>
    __name__ == "__main__" and cli()
  File "/opt/app-root/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/opt/app-root/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/opt/app-root/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/app-root/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/app-root/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/opt/app-root/lib/python3.6/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "thoth-adviser", line 463, in advise
    predictor_instance = predictor_class(**predictor_kwargs, keep_history=plot is not None)
TypeError: type object argument after ** must be a mapping, not str
```

This is caused by wrong predictor config propagation that fails to be parsed as a dict:

```yaml
        - name: THOTH_ADVISER_PREDICTOR_CONFIG
          value: '(''{}'',)'
```

**To Reproduce**
1. Go to stage environment
2. Ask for an advise
3. See the error

**Expected behavior**

Adviser should succeed.

**Comment by fridex** [comment]
This should be already fixed in thoth-common:

https://github.com/thoth-station/common/pull/991

```
* Fix predictor config propagation when scheduling adviser
```

https://github.com/thoth-station/common/pull/987


But user-api in stage is using old thoth-common:

user_api_info{version="0.6.16+storage.0.25.5.common.0.17.3"} 1.0

https://khemenu.thoth-station.ninja/metrics

**Comment by harshad16** [comment]
@fridex , the user-api in stage just needs a new roll-out I feel, as we already have the new version image in stage for user-api.
i have rolled out the deployment, can we re-check this.

**Comment by harshad16** [comment]
The user-api is now update in stage
user_api_info{version="0.6.17+storage.0.25.9.common.0.19.0"} 1.0
https://khemenu.thoth-station.ninja/metrics

**Comment by fridex** [comment]
> @fridex , the user-api in stage just needs a new roll-out I feel, as we already have the new version image in stage for user-api.
> i have rolled out the deployment, can we re-check this.

Yes, I can confirm user-api `user_api_info{version="0.6.17+storage.0.25.9.common.0.19.0"}`

I think we can proceed with https://github.com/thoth-station/thoth-application/pull/451 and test the change out.

**Comment by fridex** [comment]
Closing this issue as it is no longer relevant. @harshad16 Thanks! :+1:
