### ISSUE TITLE
THOTH_JANUSGRAPH_HOST and THOTH_JANUSGRAPH_PORT are not required

### ISSUE THREAD

**Issue by goern** [thoth-station/adviser#137]
THOTH_JANUSGRAPH_HOST and THOTH_JANUSGRAPH_PORT are not required as we have some sane defaults at https://github.com/thoth-station/storages/blob/master/thoth/storages/graph/janusgraph.py#L110-L111

https://github.com/thoth-station/adviser/blob/06d801cd72b44e95cc2e5701d9cb18f355db5e90/openshift/job-dependencyMonkey-template.yaml#L54

**Comment by harshad16** [comment]
@goern  This issue was fixed by PR #180. I guess if something else is required i can work on it, but i believe the PR #180 suffice for this issue. 
If you feel the same we can close the Issue.
