### ISSUE TITLE
Resolution was terminated based on errors for flask app

### ISSUE THREAD

**Issue by harshad16** [thoth-station/adviser#1439]
**Describe the bug**
During the execution of the [integration test](https://github.com/thoth-station/integration-tests) of thoth-station.
The thamos-advise for a flake based application stack failed in its execution.
This issue in the integration-test has some more info: https://github.com/thoth-station/integration-tests/issues/47

The adviser run was executed in the production environment. 
**cluster**: api.moc.thoth-station.ninja
**adviser**: v0.17.0

**justification** pointed towards from the error: https://thoth-station.ninja/j/error_logs
The **error log**: http://pastebin.test.redhat.com/908268

**To Reproduce**
1. Go to '[integration test](https://github.com/thoth-station/integration-tests)'
2. execute it.
3. Scroll down to pod log in the moc prod environment.

**Expected behavior**
a successful response from thoth advises

**Comment by fridex** [comment]
Based on the log, I see there are no solved releases for `markupsafe` and `itsdangerous` that are both direct dependencies of flask. It looks like transitive dependencies are not resolved yet.

**Comment by fridex** [comment]
I'll add a justification document for this.

**Comment by fridex** [comment]
> I'll add a justification document for this.

Oh, I've already done this - https://thoth-station.ninja/j/no_paths

Basically:

```
This warning might also indicate that there is no valid resolution for the requirements supplied. In such cases, “no was stack produced” error message should be printed. See the linked justification for a resolution.
```

And from the linked document - https://thoth-station.ninja/j/no_stack

```
Wait for Thoth to ingest data for unknown packages
If dependencies used in the user stack are not known to Thoth’s knowledge base, Thoth needs to ingest data to respond to user requests. This task is done in the background, transparently to the user. An appropriate message is printed to logs and the resolution process fails.
```

**Comment by fridex** [comment]
The link is not present in the log to these justifications as this an older adviser in version `0.17.0`.

**Comment by harshad16** [comment]
thanks for looking into this, exactly some of the packages are not yet resolved.
we can enable graph-refresh to run in prod if we would like to resolve this faster as we would have to wait for stage sync to complete.

**Comment by fridex** [comment]
> thanks for looking into this, exactly some of the packages are not yet resolved.
> we can enable graph-refresh to run in prod if we would like to resolve this faster as we would have to wait for stage sync to complete.

Are we able to compute solvers at such a high pace as we do right now in middletier-stage given the resources available on MOC? Otherwise, we could wait for data ingestion in stage and propagate a database dump to moc.

**Comment by fridex** [comment]
No longer relevant. I was able to resolve a flask stack. Will close this. Feel free to reopen if the issue persists.
