### ISSUE TITLE
Capture accelerator driver version and submit it to adviser

### ISSUE THREAD

**Issue by fridex** [thoth-station/adviser#1515]
**Is your feature request related to a problem? Please describe.**

As Thoth user, I would like to have recommendations that consider the accelerator driver version so that Thoth can recommend software stacks suitable for the driver version I'm using.

**Describe the solution you'd like**

Detect the driver version in thamos and submit it together with the advise request so that pipeline units can use this information when recommending software stacks.

Based on @sub-mod presentation.

**Comment by goern** [comment]
@sub-mod ping
