### ISSUE TITLE
Be notified when OOM will happen

### ISSUE THREAD

**Issue by fridex** [thoth-station/adviser#1525]
**Is your feature request related to a problem? Please describe.**

As the sub-process running in a deployment to resolve software stacks can be too memory hungry in some cases, it would be great to get notified prior to OOM happen.

**Describe the solution you'd like**

This is currently not possible given the kernel features we have. But once we will have such feature in place, adviser can be notified before the OOM would happen and could return back results computed so far (instead of failing unrecoverably on OOM signal).

**Describe alternatives you've considered**

Monitor memory consumption in the application itself, which is not nice solution.

**Comment by fridex** [comment]
/remove-lifecycle stale

This will be nice to have if the underlying platform would provide such a feature.

**Comment by goern** [comment]
How do we want to receive the notifications? via a metric+prom-alert?

/triage needs-information

**Comment by fridex** [comment]
The kernel should send information to the running process that it will be soon killed as a memory limit is approaching. This is not supported by OpenShift yet.

**Comment by fridex** [comment]
It would be great if the kernel would provide such a signal in openshift as such a solution would be reusable for any memory-hungry workloads done on openshift. For now, adviser implementation provides [a memory optimizer](https://thoth-station.ninja/docs/developers/adviser/deployment.html#memory-management) that is configured in our deployments.
