### ISSUE TITLE
Retry on OOM with more memory allocated if advise task fails on OOM

### ISSUE THREAD

**Issue by fridex** [thoth-station/adviser#1575]
**Is your feature request related to a problem? Please describe.**

If I, as a user, submit a request to have advice on software stack, I would like to make sure adviser can resolve large software stacks for me. Now, we have increased memory, but that can cause issues when scaling (the number of requests thoth can handle given resources allocated). It would be nice if we could resolve smaller software stacks with less memory and allocate more memory only if needed as a fallback scenario.

**Describe the solution you'd like**

We could tweak workflow in a way, it would run adviser with lower memory limits (e.g. 2Gi). If it encounters OOM, a subsequent task can detect adviser failed, and based on the exit code start a adviser again but with higher memory requirements.

**Describe alternatives you've considered**

Related: https://github.com/thoth-station/adviser/issues/1525 but this is more about results gathering computed so far, not to loose them.

**Comment by fridex** [comment]
This can be also interesting for "supported" consumers who can have more resources allocated (memory). This will require twice as much CPU time though. The other solution can be to run a task prior to adviser and decide whether adviser should get more resources.

**Comment by pacospace** [comment]
what about having a model that can predict/estimate how much memory is required based on the knowledge we can collect on the memory used by adviser?

**Comment by fridex** [comment]
ask aiops this :)

**Comment by goern** [comment]
@durandom

**Comment by fridex** [comment]
In our case, we might run a pre-run task that will compute how big the dependency graph is - its width and its depth. This computation could tell how much resources the adviser will eventually need to recommend a stack (also considering the recommendation type). In that case, we will just need to pre-compute a simple table for the dependency graph. This could save resources.

**Comment by fridex** [comment]
> In our case, we might run a pre-run task that will compute how big the dependency graph is - its width and its depth. This computation could tell how much resources the adviser will eventually need to recommend a stack (also considering the recommendation type). In that case, we will just need to pre-compute a simple table for the dependencies listed. This could save resources.

Which can tell Argo workflows which path in the workflow should be executed (e.g. having 3 buckets with different resource allocation - small stack, medium stack, large stack).

**Comment by fridex** [comment]
> what about having a model that can predict/estimate how much memory is required based on the knowledge we can collect on the memory used by adviser?

Just to be more clear here - we could use a model, but that would require a lot of adviser reports already available so that it can generalize for all the packages. That is also not that doable as we will have packages will not be part of reports. Hence I'm proposing the sizing based on the dependency graph size that could be computed in advance.

**Comment by fridex** [comment]
Was playing with the estimator idea, created a code that can score "how big" the dependency graph is. Sadly, there are cyclic dependencies in the ecosystem, that basically break this tabular method for scoring dependency graphs - see https://github.com/fridex/graph-memory-estimator

However, adviser does not consume much memory in general (I had ~300MiB for "large stacks"). The OOM issue might be related to some specific behavior in the dependency graph that could be avoided in predictor. Will dig into this more.

**Comment by goern** [comment]
@durandom

**Comment by fridex** [comment]
I did a few experiments with memory management in stage-ocp4 environment. I cannot reproduce the issue with the stack that originally produced OOM (which might be sometimes tricky given the resolver's stochasticity) - see for example `adviser-a111233d` where the whole pod consumed 765MiB for the original [manuela-dev stack](https://github.com/sa-mw-dach/manuela-dev/blob/eb4ff3aeb7758da09a11403684ae9cd8650d12ab/Pipfile#L6-L13), which did not consume that much memory. Also an adjusted one with tensorflow pinned to any release works - the whole pod consumed ~720MiB (see adviser-92d75e21):

```
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi-org"

[packages]
jupyter = "*"
matplotlib = "*"
numpy = "*"
pandas = "*"
scikit-learn = "*"
seaborn = "*"
tensorflow = "*"

[dev-packages]

[requires]
python_version = "3.6"
```

The issue originally reported might be caused by not all the dependencies resolved at that time. In that case, resolver might generate too many states internally until it found a suitable solution. This is described in the OOM justification https://thoth-station.ninja/j/oom.html This is just my assumption though.

It might be a good idea to keep this open. I'll decrease memory requests of adviser and let's see if we spot more OOMs.

**Comment by fridex** [comment]
@pacospace do we have stats on pod failures - how many of them failed and why?
