### ISSUE TITLE
TensorFlow API is missing "names_with_underscores"

### ISSUE THREAD

**Issue by fridex** [thoth-station/adviser#1586]
**Describe the bug**

Taking a look into TF sources:

```
_names_with_underscore = ['__version__', '__git_version__', '__compiler_version__', '__cxx11_abi_flag__', '__monolithic_build__', '__operators__']
__all__ = [_s for _s in dir() if not _s.startswith('_')]
__all__.extend([_s for _s in _names_with_underscore])
```
We do not gather all the symbols, specifically, we miss "_names_with_underscore" in the aggregated API

**To Reproduce**
1. Use a TensorFlow application that uses one of the symbols stated in the `_names_with_underscore` listing
2. Trigger `thamos advise`
3. See the adviser did not produce expected results (did not find API symbols subset)

**Expected behavior**

Adviser should consider also "`name_with_underscore`".

**Comment by goern** [comment]
@fridex do you take care about this?

**Comment by fridex** [comment]
> @fridex do you take care about this?

See the linked issues. PRs were sent.
