### ISSUE TITLE
create advise wrt https://thoth-station.ninja/j/mkl_libs

### ISSUE THREAD

**Issue by goern** [thoth-station/adviser#1604]
**Is your feature request related to a problem? Please describe.**
Let's turn the warning message https://thoth-station.ninja/j/mkl_libs into an actionable item. Which base image could be used to have the best libraries? Which libraries to use?

/kind feature
/priority important-longterm

**Comment by fridex** [comment]
Related: https://github.com/thoth-station/thamos/issues/579

**Comment by fridex** [comment]
/remove-lifecycle stale

The recommendation should point to a Thoth s2i base image that has the correct MKL setup. We can do so once such S2I base will be available.

**Comment by fridex** [comment]
Do we have an image where mkl libs would be present (as RPM packages we can detect)?

CC @harshad16 @pacospace @goern

**Comment by goern** [comment]
I'm not aware of that. @sub-mod ?

**Comment by goern** [comment]
ping @sub-mod

**Comment by sub-mod** [comment]
will [this](https://hub.docker.com/r/intel/intel-optimized-tensorflow) do ?

**Comment by fridex** [comment]
> will [this](https://hub.docker.com/r/intel/intel-optimized-tensorflow) do ?

Sadly, only Ubuntu-based. Do we have any plans and use cases to have UBI/Fedora based?
