### ISSUE TITLE
Do not recommend using upstream tensorflow==2.4.0 when AVX2 instruction set is not present

### ISSUE THREAD

**Issue by fridex** [thoth-station/adviser#1616]
**Is your feature request related to a problem? Please describe.**

See issues reported upstream in https://github.com/tensorflow/tensorflow/issues/45866 and https://github.com/tensorflow/tensorflow/issues/45744

**Describe the solution you'd like**

Recommend not to use TensorFlow==2.4.0 when AVX2 instruction set is not present on the machine.

**Comment by goern** [comment]
@fridex this is done, right?

**Comment by fridex** [comment]
Yes, this can be closed.

**Comment by mihaimaruseac** [comment]
Just an update, TF 2.4.1 has been released and removes the AVX2 restriction. Apologies for the issues caused.

**Comment by fridex** [comment]
Thanks, @mihaimaruseac. The resolver's pipeline unit is specific to tensorflow==2.4.0 coming from PyPI so this should be correctly handled:

https://github.com/thoth-station/adviser/blob/f9284ca2dde8d500173af1dc1533e08f3b37c282/thoth/adviser/sieves/tensorflow/tf_240_avx2.py#L88-L94

https://thoth-station.ninja/j/tf_240_avx2.html

Thanks again for this update! :+1:
