### ISSUE TITLE
Create a pipeline unit which is specific for checking CUDA and GPU model

### ISSUE THREAD

**Issue by fridex** [thoth-station/adviser#1627]
**Is your feature request related to a problem? Please describe.**

I, as a developer, would like to know if my CUDA driver is compatible with a GPU available so that I'm sure the application will work well.

**Describe the solution you'd like**

Implement a pipeline unit that would be run when a GPU model and CUDA are supplied. In such a case, the pipeline unit would be responsible for eliminating GPUs that do not work properly with the CUDA version available. If the CUDA version available does not work properly with the available GPU, treat the resolution process as if no CUDA/GPU would be available.

Possibly, split the implementation into multiple pipeline units if it helps with maintainability.

**Comment by pacospace** [comment]
cc @sub-mod
