### ISSUE TITLE
Extend ABI compat sieve so that it checks ABI symbols exported by Thoth base images

### ISSUE THREAD

**Issue by fridex** [thoth-station/adviser#1631]
**Is your feature request related to a problem? Please describe.**

As of now, we check for "any" base image which matches provided configuration:

https://github.com/thoth-station/adviser/blob/fdf2091300c1c49c3544a7a2bffb7cec8a43e8b1/thoth/adviser/sieves/abi_compat.py#L56-L63

This can be extended so that the pipeline unit starts benefiting from the base image info as described in https://github.com/thoth-station/s2i-thoth/issues/128

**Describe the solution you'd like**

- [x] create a query that queries the database for the symbols available and used in s2i-thoth base images - https://github.com/thoth-station/storages/pull/2195
- [x] adjust the pipeline unit so that it starts using the newly introduced query - the pipeline unit was reimplemented https://github.com/thoth-station/adviser/pull/1632
- [x] make sure the s2i-thoth base container images are registered on management-api endpoint to disable `is_external` container image

**Comment by goern** [comment]
/sig advisor
/sig documentation

+1

**Comment by fridex** [comment]
All the bullets are implemented. We can push components to stage and have this in place. Closing.
