### ISSUE TITLE
Resolver was killed as allocated CPU time was exceeded

### ISSUE THREAD

**Issue by goern** [thoth-station/adviser#1645]
**Describe the bug**
integration test fail with `  "error_msg": "Resolver was killed as allocated CPU time was exceeded - https://thoth-station.ninja/j/cpu_time_exceeded",`

**To Reproduce**
1. Go to 'https://prow.operate-first.cloud/'
2. Have a look at an integration test log

**Expected behavior**
advise workflow delivers result.

/kind bug
/sig devops

**Comment by fridex** [comment]
What was the software stack used in this case? I wonder if we have all the data ready.

**Comment by fridex** [comment]
Closing this one, feel free to reopen - I will need a more detailed description to track the issue.
