### ISSUE TITLE
Add support for multiple platforms

### ISSUE THREAD

**Issue by fridex** [thoth-station/adviser#1782]
**Is your feature request related to a problem? Please describe.**

As of now, we resolve just for linux x86_64. If we plan to support multiple architectures, we will need to perform few minor changes in sources.

**Describe the solution you'd like**

- resolver should take into account platform provided

https://github.com/thoth-station/adviser/blob/665aa67bd332e0a44d13b97cbe9c7ae103d7b324/thoth/adviser/resolver.py#L843-L851

- thoth-storages module indexes should be adjusted in a way they consider also platform (related https://github.com/thoth-station/storages/pull/2263)

This is blocked until https://github.com/thoth-station/storages/issues/2181 is resolved (it will be implemented based on the solution in the linked PR).

**Comment by goern** [comment]
see https://github.com/thoth-station/core/blob/master/community/labels.md#lifecycle/frozen

**Comment by fridex** [comment]
Let's close this, we can reopen once a new platfom support will be requested.

/close
