### ISSUE TITLE
Introduce new justifications

### ISSUE THREAD

**Issue by pacospace** [thoth-station/adviser#1822]
**Is your feature request related to a problem? Please describe.**
Introduce new justifications to explain messages received.

**Describe the solution you'd like**
After an initial analysis of adviser reports, we found out some messages provided to users do not correspond to any justifications; links:

```
adviser_version`justification`level`count
0.26.0`https://thoth-station.ninja/j/platform`WARNING`35
0.26.0`https://thoth-station.ninja/j/no_observations`INFO`738
0.26.0`https://thoth-station.ninja/j/buildtime_error`WARNING`12711
0.26.0`Boot pipeline unit 'PlatformBoot' failed: No platform conforming to 'win-amd64' found in the database`ERROR`1
0.26.0`Cannot satisfy direct dependencies - direct dependencies of type 'tensorflow' were removed by pipeline sieves`ERROR`1
0.26.0`Cannot satisfy direct dependencies - direct dependencies of type 'pandas' were removed by pipeline sieves`ERROR`1
0.26.0`Cannot satisfy direct dependencies - direct dependencies of type 'bs4' were removed by pipeline sieves`ERROR`2
```
It would be nice to have link as `https://thoth-station.ninja/j/{justification_name}` for consistency.

adviser version considered between `2021-03-01` and `2021-04-14` was `0.26.0`

**Describe alternatives you've considered**

**Additional context**

**Comment by fridex** [comment]
Thanks for the analysis.
 
> It would be nice to have link as `https://thoth-station.ninja/j/{justification_name}` for consistency.

It's not directly clear to me what is the issue here. The linked justifications exist:

https://thoth-station.ninja/j/platform
https://thoth-station.ninja/j/no_observations
https://thoth-station.ninja/j/buildtime_error

Could you please elaborate on this one?

**Comment by pacospace** [comment]
> Thanks for the analysis.
> 
> > It would be nice to have link as `https://thoth-station.ninja/j/{justification_name}` for consistency.
> 
> It's not directly clear to me what is the issue here. The linked justifications exist:
> 
> https://thoth-station.ninja/j/platform
> https://thoth-station.ninja/j/no_observations
> https://thoth-station.ninja/j/buildtime_error
> 
> Could you please elaborate on this one?

The issue here is that there are justifications not in that format

```
0.26.0`Boot pipeline unit 'PlatformBoot' failed: No platform conforming to 'win-amd64' found in the database`ERROR`1
0.26.0`Cannot satisfy direct dependencies - direct dependencies of type 'tensorflow' were removed by pipeline sieves`ERROR`1
0.26.0`Cannot satisfy direct dependencies - direct dependencies of type 'pandas' were removed by pipeline sieves`ERROR`1
0.26.0`Cannot satisfy direct dependencies - direct dependencies of type 'bs4' were removed by pipeline sieves`ERROR`2
```
