### ISSUE TITLE
New justification to include in thoth recommendations for opencv-python

### ISSUE THREAD

**Issue by pacospace** [thoth-station/adviser#1823]
**Is your feature request related to a problem? Please describe.**
Create new justification for https://github.com/opencv/opencv-python/issues/464

**Describe the solution you'd like**

- [ ] collect observations on this error (solver??)
- [ ] (intern project to include clustered solver errors into advise justifications)
- [ ] New justification to include in thoth recommendations to filter certain versions.

**Describe alternatives you've considered**

**Additional context**

**Comment by fridex** [comment]
Does not look relevant - see the upstream issue discussion.

/close
