### ISSUE TITLE
advise failure with CPU time exceed

### ISSUE THREAD

**Issue by harshad16** [thoth-station/adviser#1846]
**Describe the bug**
Advise on the following stack is [elyra-aidevsecops-tutorial-download-dataset](https://github.com/thoth-station/elyra-aidevsecops-tutorial/tree/master/overlays/download-dataset) failed.

Details:
adviser_run_id: `adviser-210505171314-ce172fbe870cabed`
error: "Resolver was killed as allocated CPU time was exceeded - https://thoth-station.ninja/j/cpu_time_exceeded"

```
  | git_repo                                                             | runtime_environment     | user_stack  | static_analysis |
  | https://github.com/thoth-station/elyra-aidevsecops-tutorial          | download-dataset        | with        | without         |
```

**Additional context**
Related-to: https://github.com/thoth-station/integration-tests/issues/79

**Comment by fridex** [comment]
Thanks for digging into this! 👍🏻 

This will probably need some debugging, looks like a bug in resolver. 😞

**Comment by goern** [comment]
@harshad16 what deployment was it?

/kind bug
/assign @fridex 
/triage needs-information

**Comment by harshad16** [comment]
it was the zero-prod cluster deployment
added the label now to reflect that.

**Comment by harshad16** [comment]
Same happened for: 

adviser-210507043539-b73c08f0ed0c0733
https://github.com/thoth-station/integration-tests/blob/1afe5dd551211e72bd6e94073127769dd0a768c2/features/thamos_advise.feature#L29

adviser-210507045301-762e81770d822d9b
https://github.com/thoth-station/integration-tests/blob/1afe5dd551211e72bd6e94073127769dd0a768c2/features/thamos_advise.feature#L31

**Comment by fridex** [comment]
> adviser-210507045301-762e81770d822d9b
> https://github.com/thoth-station/integration-tests/blob/1afe5dd551211e72bd6e94073127769dd0a768c2/features/thamos_advise.feature#L31

`inference` uses `security` recommendation type - in that case, security indicators step does not allow using packages for which security indicators haven't aggregated data:

https://github.com/thoth-station/adviser/blob/master/thoth/adviser/steps/security_indicators.py#L142-L159

Switching to `stable` recommendation type (in which case the resolution is not strict about security data) works - it looks like this case is a "missing data" problem. We should probably be more explicit about this in docs.

**Comment by goern** [comment]
any conclusion or follow up action on this on?

**Comment by fridex** [comment]
> Switching to `stable` recommendation type (in which case the resolution is not strict about security data) works - it looks like this case is a "missing data" problem. We should probably be more explicit about this in docs.

This does not look like an adviser bug but rather missing data.

Closing.

/close

> any conclusion or follow up action on this on?

Ingest required data.
