### ISSUE TITLE
adviser failed due to oom issue

### ISSUE THREAD

**Issue by harshad16** [thoth-station/adviser#1850]
**Describe the bug**
while querying for advises from api.moc.thoth-station.ninja host, got the following issue
`Resolver was killed as allocated memory has been exceeded (OOM) - https://thoth-station.ninja/j/oom`

Adviser_id: adviser-210507061559-4da1a071262ab059
stack: https://github.com/aicoe-aiops/ocp-ci-analysis
![adviser-4da](https://user-images.githubusercontent.com/14028058/117407832-1cda3500-aedd-11eb-8e58-7558d1289258.png)

should we increase the memory limits?

**Comment by goern** [comment]
/kind bug
/traige needs-information

is this still valid?

**Comment by goern** [comment]
@harshad16 ping

**Comment by harshad16** [comment]
will recheck on this one to valid.
