### ISSUE TITLE
Introduce labels to the resolution process

### ISSUE THREAD

**Issue by fridex** [thoth-station/adviser#1885]
**Is your feature request related to a problem? Please describe.**

Considering two users - user A and user B, both from different teams.

Even though user A and user B are using the same recommendation engine, users would like to have different resolutions specific to our needs - e,g, team A prefers packages from a different index. We can solve this by introducing labels that would be sent with the request and make sure the right set of pipeline units is registered to satisfy a request to the recommendation engine based on the team that the request triggered.

**Comment by goern** [comment]
This would be another dimension for the user request? so we have recommendation_type and a set of labels (plus all the other inputs)?

/kind feature
/kind demo
/triage needs-information

**Comment by fridex** [comment]
> This would be another dimension for the user request? so we have recommendation_type and a set of labels (plus all the other inputs)?

Yes. We have a use case where one team will need a different set of pipeline units registered in the resolution process - an example could be the Python maintenance team that would like to flag packages stored on their index only for their test suite (they will maintain a prescription.yaml file with this list on their own). They could specify that on thamos side when they ask for advise:

```
thamos advise --label team=python_maint
```

In that case, it would be a resolution specific for the python_main team in the "central brain".

This approach can also be reused for https://github.com/thoth-station/core/issues/272
