### ISSUE TITLE
Limit impact of security scoring with respect to security indicators run

### ISSUE THREAD

**Issue by fridex** [thoth-station/adviser#1911]
**Describe the bug**

When running advises with `recommendation_type` set to `security`, resolver often fails to find a solution. The reason behind this is in the security scoring which has not enough data aggregated.

**To Reproduce**
1. Run an advise on a software stack with `recommendation_type` set to `security`
2. See the error produced

**Expected behavior**

Adviser should succeed.

As this is due to missing data, we can avoid the failure by being not that strict with security scoring (until we have data in place).

**Additional context**

Related: https://github.com/thoth-station/adviser/issues/1846

**Comment by goern** [comment]
@fridex are you working on this?

**Comment by fridex** [comment]
> @fridex are you working on this?

There is nothing to work on. This is caused by missing data. Otherwise, https://github.com/thoth-station/thoth-application/pull/1665 will make sure security indicators are not considered during the resolution process.

**Comment by goern** [comment]
so this is more a reminder than a bug?

**Comment by fridex** [comment]
> so this is more a reminder than a bug?

Yes, we can try to compute missing data together with https://github.com/thoth-station/thoth-application/issues/1764

**Comment by goern** [comment]
@fridex @harshad16 what is the status of this? can you give a short overview of the state of data ingestion wrt security indicators?

**Comment by fridex** [comment]
They are low priority now. handling solver workflows. If we will not ingest solver data, security indicators data are useless.

**Comment by goern** [comment]
what is the status of this one?!
