### ISSUE TITLE
Avoid using pip install --dev for seldon dependency mismatch

### ISSUE THREAD

**Issue by isabelizimm** [thoth-station/adviser#1945]
**Is your request related to a problem? Please describe.**
I have this [Pipfile](https://github.com/aicoe-aiops/pet-image-detection/blob/main/Pipfile) with `seldon-core` under `[dev-packages]` and all other under `[packages]` as a workaround since Seldon has conflicting subdependencies with the other packages used. This creates problems when deploying the notebook image hosted on Operate First since `seldon-core` will not be installed for users.

**Describe the solution you'd like**
Resolution for subdependencies or way for users to avoid having to pip install in the `pet-image-detection` demo on Op1st

**Additional context**
Slack discussion [here](https://operatefirst.slack.com/archives/C01RMPVUUK1/p1624951729296700?thread_ts=1624901720.286400&cid=C01RMPVUUK1)

CC: @pacospace

**Comment by pacospace** [comment]
> **Is your request related to a problem? Please describe.**
> I have this [Pipfile](https://github.com/aicoe-aiops/pet-image-detection/blob/main/Pipfile) with `seldon-core` under `[dev-packages]` and all other under `[packages]` as a workaround since Seldon has conflicting subdependencies with the other packages used. This creates problems when deploying the notebook image hosted on Operate First since `seldon-core` will not be installed for users.
> 
> **Describe the solution you'd like**
> Resolution for subdependencies or way for users to avoid having to pip install in the `pet-image-detection` demo on Op1st
> 
> **Additional context**
> Slack discussion [here](https://operatefirst.slack.com/archives/C01RMPVUUK1/p1624951729296700?thread_ts=1624901720.286400&cid=C01RMPVUUK1)
> 
> CC: @pacospace

Thanks @isabelizimm!!!, Can you  confirm the issue you encounter is:

```
[pipenv.exceptions.ResolutionFailure]: Warning: Your dependencies could not be resolved. You likely have a mismatch in your sub-dependencies.
  First try clearing your dependency cache with $ pipenv lock --clear, then try the original command again.
 Alternatively, you can use $ pipenv install --skip-lock to bypass this mechanism, then run $ pipenv graph to inspect the situation.
  Hint: try $ pipenv lock --pre if it is a pre-release dependency.
ERROR: Could not find a version that matches click<8.0,<8.1,>=5.1,>=8.0.0a1 (from seldon-core==1.9.0->-r /tmp/pipenvle8k3yavrequirements/pipenv-nehpfx0o-constraints.txt (line 2))
Tried: 0.1, 0.1, 0.2, 0.2, 0.3, 0.3, 0.4, 0.4, 0.5, 0.5, 0.5.1, 0.5.1, 0.6, 0.6, 0.7, 0.7, 1.0, 1.0, 1.1, 1.1, 2.0, 2.0, 2.1, 2.1, 2.2, 2.2, 2.3, 2.3, 2.4, 2.4, 2.5, 2.5, 2.6, 2.6, 3.0, 3.0, 3.1, 3.1, 3.2, 3.2, 3.3, 3.3, 4.0, 4.0, 4.1, 4.1, 5.0, 5.0, 5.1, 5.1, 6.0, 6.0, 6.1, 6.1, 6.2, 6.2, 6.3, 6.3, 6.4, 6.4, 6.5, 6.6, 6.6, 6.7, 6.7, 7.0, 7.0, 7.1, 7.1, 7.1.1, 7.1.1, 7.1.2, 7.1.2, 8.0.0, 8.0.0, 8.0.1, 8.0.1
Skipped pre-versions: 6.7.dev0, 8.0.0a1, 8.0.0a1, 8.0.0rc1, 8.0.0rc1
There are incompatible versions in the resolved dependencies:
  click<8.0,>=5.1 (from flask==1.1.4->seldon-core==1.9.0->-r /tmp/pipenvle8k3yavrequirements/pipenv-nehpfx0o-constraints.txt (line 2))
  click<8.1,>=8.0.0a1 (from seldon-core==1.9.0->-r /tmp/pipenvle8k3yavrequirements/pipenv-nehpfx0o-constraints.txt (line 2))

```

**Comment by isabelizimm** [comment]
Yes! That is the issue I hit. I've tried `thamos advise`  with all dependencies moved into `[packages]`, but hit the error:
`2021-06-29 17:57:36,498 [14749] ERROR    thamos.lib: Failed to obtain status from Thoth: HTTPSConnectionPool(host='khemenu.thoth-station.ninja', port=443): Max retries exceeded with url: /api/v1/advise/python/adviser-210629175411-46498ec1c2853df2 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f75140db5e0>: Failed to establish a new connection: [Errno 111] Connection refused'))`

**Comment by pacospace** [comment]
> Yes! That is the issue I have.
> 
> I've tried `thamos advise` with all dependencies moved into `[packages]`, but have the error:
> `2021-06-29 17:57:36,498 [14749] ERROR thamos.lib: Failed to obtain status from Thoth: HTTPSConnectionPool(host='khemenu.thoth-station.ninja', port=443): Max retries exceeded with url: /api/v1/advise/python/adviser-210629175411-46498ec1c2853df2 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f75140db5e0>: Failed to establish a new connection: [Errno 111] Connection refused'))`

Sorry there is an outage currently :/ 

In any case I tried:

```
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]
seldon-core = "*"

[dev-packages]

[requires]
python_version = "3.8"

```

and the issue, persist, it is not a conflict with other packages, but constraints in seldon-core, not sure why but they come from: https://github.com/SeldonIO/seldon-core/blob/master/python/setup.py

specifically `"Flask<2.0.0"` and `"click >= 8.0.0a1, < 8.1"` which lead to the above error. Let's open an issue upstream for this!

**Comment by pacospace** [comment]
> > Yes! That is the issue I have.
> > I've tried `thamos advise` with all dependencies moved into `[packages]`, but have the error:
> > `2021-06-29 17:57:36,498 [14749] ERROR thamos.lib: Failed to obtain status from Thoth: HTTPSConnectionPool(host='khemenu.thoth-station.ninja', port=443): Max retries exceeded with url: /api/v1/advise/python/adviser-210629175411-46498ec1c2853df2 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f75140db5e0>: Failed to establish a new connection: [Errno 111] Connection refused'))`
> 
> Sorry there is an outage currently :/
> 
> In any case I tried:
> 
> ```
> [[source]]
> url = "https://pypi.org/simple"
> verify_ssl = true
> name = "pypi"
> 
> [packages]
> seldon-core = "*"
> 
> [dev-packages]
> 
> [requires]
> python_version = "3.8"
> ```
> 
> and the issue, persist, it is not a conflict with other packages, but constraints in seldon-core, not sure why but they come from: https://github.com/SeldonIO/seldon-core/blob/master/python/setup.py
> 
> specifically `"Flask<2.0.0"` and `"click >= 8.0.0a1, < 8.1"` which lead to the above error. Let's open an issue upstream for this!

but It does not fail running `pip install seldon-core`

**Comment by pacospace** [comment]
> > > Yes! That is the issue I have.
> > > I've tried `thamos advise` with all dependencies moved into `[packages]`, but have the error:
> > > `2021-06-29 17:57:36,498 [14749] ERROR thamos.lib: Failed to obtain status from Thoth: HTTPSConnectionPool(host='khemenu.thoth-station.ninja', port=443): Max retries exceeded with url: /api/v1/advise/python/adviser-210629175411-46498ec1c2853df2 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f75140db5e0>: Failed to establish a new connection: [Errno 111] Connection refused'))`
> > 
> > 
> > Sorry there is an outage currently :/
> > In any case I tried:
> > ```
> > [[source]]
> > url = "https://pypi.org/simple"
> > verify_ssl = true
> > name = "pypi"
> > 
> > [packages]
> > seldon-core = "*"
> > 
> > [dev-packages]
> > 
> > [requires]
> > python_version = "3.8"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > and the issue, persist, it is not a conflict with other packages, but constraints in seldon-core, not sure why but they come from: https://github.com/SeldonIO/seldon-core/blob/master/python/setup.py
> > specifically `"Flask<2.0.0"` and `"click >= 8.0.0a1, < 8.1"` which lead to the above error. Let's open an issue upstream for this!
> 
> but It does not fail running `pip install seldon-core`

Actually this seems to work @isabelizimm having only seldon-core:

```
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]
seldon-core = "*"
Flask = "<1.1.3"

[dev-packages]

[requires]
python_version = "3.8"
```

Do you have a strong requirement on having `tensorflow` and `seldon-core` on the same image/notebook? From the look a the notebook it seems it should be possible, wdyt?

**Comment by isabelizimm** [comment]
> Do you have a strong requirement on having `tensorflow` and `seldon-core` on the same image/notebook for your tutorial? From a first look a the notebook it seems it should be possible to split it, wdyt?

The current iteration does not need both in the same image, so this is fine for now!

**Comment by fridex** [comment]
Our prod environment is currently under maintenance, as @pacospace pointed out above. [Here is a Pipfile.lock](https://gist.github.com/fridex/035b3900c1c1ea31c677b99c98c2aa56) for the request made in stage environment ([adviser-210630071435-63c4d14e59275470](https://stage.thoth-station.ninja/api/v1/advise/python/adviser-210630071435-63c4d14e59275470), RH VPN required). It looks like the resolver suggested using older flask/tensorflow/sendon-core versions (we might have also data for older releases, so the resolved dependencies are not necessarily "latest"). It might be good to give additional version requirements to the stack if you rely on specific features or expect specific releases.

One of the issues I observed with Pipenv - it does not consider older versions of direct dependencies all the time, thus it fails with an error reported to you when there is a clash with dependencies.

**Comment by pacospace** [comment]
> Our prod environment is currently under maintenance, as @pacospace pointed out above. [Here is a Pipfile.lock](https://gist.github.com/fridex/035b3900c1c1ea31c677b99c98c2aa56) for the request made in stage environment ([adviser-210630071435-63c4d14e59275470](https://stage.thoth-station.ninja/api/v1/advise/python/adviser-210630071435-63c4d14e59275470), RH VPN required). It looks like the resolver suggested using older flask/tensorflow/sendon-core versions (we might have also data for older releases, so the resolved dependencies are not necessarily "latest"). It might be good to give additional version requirements to the stack if you rely on specific features or expect specific releases.
> 
> One of the issues I observed with Pipenv - it does not consider older versions of direct dependencies all the time, thus it fails with an error reported to you when there is a clash with dependencies.

Sorry @fridex I cannot find the request on Ceph to retrieve the inputs used, so we can set aicoe-ci for @isabelizimm to build her image.

Can you share the inputs please? Thanks!!!

**Comment by fridex** [comment]
> Sorry @fridex I cannot find the request on Ceph to retrieve the inputs used, so we can set aicoe-ci for @isabelizimm to build her image.
> 
> Can you share the inputs please? Thanks!!!

@harshad16 could you point @pacospace to the location where stage documents backup was created? Thanks! 👍🏻

**Comment by pacospace** [comment]
> > Sorry @fridex I cannot find the request on Ceph to retrieve the inputs used, so we can set aicoe-ci for @isabelizimm to build her image.
> > Can you share the inputs please? Thanks!!!
> 
> @harshad16 could you point @pacospace to the location where stage documents backup was created? Thanks! 👍🏻

Now that you mentioned backup, found it :) Thanks @fridex @harshad16!!

**Comment by fridex** [comment]
> Sorry @fridex I cannot find the request on Ceph to retrieve the inputs used, so we can set aicoe-ci for @isabelizimm to build her image.

BTW I used the [Pipfile from the original report](https://github.com/aicoe-aiops/pet-image-detection/blob/main/Pipfile) and [the lock file produced is linked](https://gist.github.com/fridex/035b3900c1c1ea31c677b99c98c2aa56).

**Comment by pacospace** [comment]
> > Sorry @fridex I cannot find the request on Ceph to retrieve the inputs used, so we can set aicoe-ci for @isabelizimm to build her image.
> 
> BTW I used the [Pipfile from the original report](https://github.com/aicoe-aiops/pet-image-detection/blob/main/Pipfile) and [the lock file produced is linked](https://gist.github.com/fridex/035b3900c1c1ea31c677b99c98c2aa56).

Thanks @fridex. only question I have is why in the request, the runtime environment is rhel-8-py36 (pasted adviser-210630071435-63c4d14e59275470.request below)? it should have failed if the pipfile requires 3.8

```
{
  "application_stack": {
    "requirements": "[[source]]\nurl = \"https://pypi.org/simple\"\nverify_ssl = true\nname = \"pypi\"\n\n[packages]\nalibi = \"*\"\nmatplotlib = \"*\"\nnumpy = \"*\"\ntensorflow = \"*\"\nseldon-core = \"*\"\n\n[dev-packages]\n\n[requires]\npython_version = \"3.8\"\n",
    "requirements_lock": ""
  },
  "constraints": [],
  "count": 1,
  "debug": false,
  "dev": false,
  "github_base_repo_url": null,
  "github_check_run_id": null,
  "github_event_type": null,
  "github_installation_id": null,
  "job_id": "adviser-210630071435-63c4d14e59275470",
  "justification": null,
  "kebechet_metadata": null,
  "labels": null,
  "library_usage": {
    "report": {
      "flask": [
        "flask.Flask"
      ],
      "tensorflow": [
        "tensorflow.Session",
        "tensorflow.constant"
      ]
    },
    "version": "0.1.0"
  },
  "limit": null,
  "origin": "git@github.com:fridex/thamos",
  "recommendation_type": "latest",
  "runtime_environment": {
    "base_image": null,
    "cuda_version": null,
    "cudnn_version": null,
    "hardware": {
      "cpu_family": null,
      "cpu_model": null,
      "gpu_model": null
    },
    "mkl_version": null,
    "name": "my_project",
    "openblas_version": null,
    "openmpi_version": null,
    "operating_system": {
      "name": "rhel",
      "version": "8.0"
    },
    "platform": null,
    "python_version": "3.6",
    "recommendation_type": null
  },
  "source_type": "CLI",
  "stack_info": null
}% 
```

**Comment by harshad16** [comment]
>  to the location where stage documents backup was created? Thanks! 👍🏻  

Yes , the the backup is named ocp4-stage-backup in the psi s3 cluster.

**Comment by fridex** [comment]
> > > Sorry @fridex I cannot find the request on Ceph to retrieve the inputs used, so we can set aicoe-ci for @isabelizimm to build her image.
> > 
> > 
> > BTW I used the [Pipfile from the original report](https://github.com/aicoe-aiops/pet-image-detection/blob/main/Pipfile) and [the lock file produced is linked](https://gist.github.com/fridex/035b3900c1c1ea31c677b99c98c2aa56).
> 
> Thanks @fridex. only question I have is why in the request, the runtime environment is rhel-8-py36 (pasted adviser-210630071435-63c4d14e59275470.request below)? it should have failed if the pipfile requires 3.8? or it is give precedence to the pipfile?

Thoth's configuration file takes precedence when it comes to Python version over the one stated in Pipfile. The resolved stack is thus Python 3.6 specific. You can try to run it under Python 3.8 though until we ingest Python 3.8 data.

**Comment by pacospace** [comment]
> > > > Sorry @fridex I cannot find the request on Ceph to retrieve the inputs used, so we can set aicoe-ci for @isabelizimm to build her image.
> > > 
> > > 
> > > BTW I used the [Pipfile from the original report](https://github.com/aicoe-aiops/pet-image-detection/blob/main/Pipfile) and [the lock file produced is linked](https://gist.github.com/fridex/035b3900c1c1ea31c677b99c98c2aa56).
> > 
> > 
> > Thanks @fridex. only question I have is why in the request, the runtime environment is rhel-8-py36 (pasted adviser-210630071435-63c4d14e59275470.request below)? it should have failed if the pipfile requires 3.8? or it is give precedence to the pipfile?
> 
> Thoth's configuration file takes precedence when it comes to Python version over the one stated in Pipfile. The resolved stack is thus Python 3.6 specific. You can try to run it under Python 3.8 though until we ingest Python 3.8 data.

Thanks for clarifying, then we need to ask for py 3.8, as the image required by @isabelizimm needs python 3.8.

**Comment by fridex** [comment]
> Thanks for clarifying, then we need to ask for py 3.8, as the image required by @isabelizimm needs python 3.8. will try with prod

You can still try to run dependencies resolved for Python 3.6 under Python 3.8 - it does not mean the stack will work for sure, but if it blocks some work, you can try it. I see some dependencies specific for older versions of Python, but that does not mean they are preventing from trying the resolved dependencies on Python 3.8.

**Comment by goern** [comment]
what is the state of this issue?

**Comment by pacospace** [comment]
@isabelizimm did you check the stack provided by @fridex, does it work even if created for python 3.6?

**Comment by isabelizimm** [comment]
@pacospace been looking at this today--the release does not push to quay with the 3.6 stack, unfortunately : (

**Comment by fridex** [comment]
> @pacospace been looking at this today--the release does not push to quay with the 3.6 stack, unfortunately : (

Most probably `--deploy` check fails. Are you using this [Pipfile](https://github.com/aicoe-aiops/pet-image-detection/blob/main/Pipfile)?

**Comment by isabelizimm** [comment]
> Most probably `--deploy` check fails. Are you using this [Pipfile](https://github.com/aicoe-aiops/pet-image-detection/blob/main/Pipfile)?

Yep! Using that Pipfile + the lock that you provided.

**Comment by fridex** [comment]
> > Most probably `--deploy` check fails. Are you using this [Pipfile](https://github.com/aicoe-aiops/pet-image-detection/blob/main/Pipfile)?
> 
> Yep! Using that Pipfile + the lock that you provided.

Could you try with https://github.com/aicoe-aiops/pet-image-detection/pull/8?

**Comment by isabelizimm** [comment]
> > > Most probably `--deploy` check fails. Are you using this [Pipfile](https://github.com/aicoe-aiops/pet-image-detection/blob/main/Pipfile)?
> > 
> > 
> > Yep! Using that Pipfile + the lock that you provided.
> 
> Could you try with [aicoe-aiops/pet-image-detection#8](https://github.com/aicoe-aiops/pet-image-detection/pull/8)?

No luck with that Pipfile either :(

**Comment by fridex** [comment]
Does the build succeed? If not, could you post build logs?

**Comment by fridex** [comment]
The bot closed the issue. Please let us know if there is anything more we could help with. Thanks for the report.
