### ISSUE TITLE
Notify about possible dependency graph issues when user's stack is supplied

### ISSUE THREAD

**Issue by fridex** [thoth-station/adviser#1990]
**Is your feature request related to a problem? Please describe.**

When a user submits a lock file with the request, we do not verify whether the lock file is actually correct. This can introduce issues in the dependency graph reported as it relies on adviser's dependency information.

**Describe the solution you'd like**

Warn when `thamos graph` is used on user's lock file.

**Comment by goern** [comment]
Is there something that we can do if we send a warning? any diff to heal the problematic lock file?

/priority important-soon

**Comment by fridex** [comment]
> Is there something that we can do if we send a warning? any diff to heal the problematic lock file?


As the lock file was not produced by our resolver, we cannot rely on its correctness. If users supply a request without a lock file (or we recommend not to use the lockfile they sent us) we can show the dependency graph.
