### ISSUE TITLE
Add environment in URL to the package in search UI

### ISSUE THREAD

**Issue by fridex** [thoth-station/adviser#2223]
**Is your feature request related to a problem? Please describe.**

As a Thoth user, I would like to browse information about a Python package by accessing a link provided by adviser:

https://github.com/thoth-station/adviser/blob/3048e7c6edc3388e2b73d26c939c02a87cac6c8b/thoth/adviser/wraps/thoth_search_package.py#L34

As the recommended package is specific to `{os_name}`, `{os_version}`, `{python_version}`, `{package_name}`, `{package_version}`, `{index_url}`, all these should be part of the routing to Thoth Search UI.

**Describe the solution you'd like**

Add information about runtime environment and `index_url` to Thoth Search UI URL specific to the given package.

**Comment by fridex** [comment]
CC @Gkrumbach07

**Comment by goern** [comment]
@fridex @Gkrumbach07 what is the prio of this feature?

**Comment by Gkrumbach07** [comment]
> @fridex @Gkrumbach07 what is the prio of this feature?

Feature is implemented on search already using the URL name/version/index/osname/is version/pyversion.
