### ISSUE TITLE
Adviser suggests environments that could be soon purged

### ISSUE THREAD

**Issue by fridex** [thoth-station/adviser#2245]
**Describe the bug**

As of now, adviser suggests to use environments that could be soon purged. The reason behind it is the reporting that queries the database:

https://github.com/thoth-station/adviser/blob/5a506418169b704449b545d98fb2edee7d905df9/thoth/adviser/boots/solved_software_environment.py#L81

Rather than obtaining environments from the database, adviser should rather check which environments are available based on solvers configmap similarly as user-api suggests environments:

https://github.com/thoth-station/user-api/blob/1376a96595c7ca3dc560f601de51beb2a61d339f/thoth/user_api/api_v1.py#L1390-L1398

Note, however, that the adviser pod does not have permission to obtain configmaps. Rather, deployment should be adjusted so that solvers configuration is supplied via environment variables to adviser.

**To Reproduce**
1. Provide an unknown environment and ask test environment for an advisory
2. Test environment has some environments that are not purged yet
3. See suggestions to use environments that are not configured in solvers config map

**Expected behavior**

Adviser should suggest to use environments based on the entries in solvers configmap.

**Additional context**

Possible solution:

1. Adjust adviser deployment so that solvers configmap (ex. [for prod](https://github.com/thoth-station/thoth-application/blob/df80b4d33af98ec4f3a58cbf4c7e5c4725ee28a4/core/overlays/moc-prod/common/configmaps.yaml#L38-L41)) content is propagated to adviser as an environment variable
2. The environment variable is read in adviser and the content is parsed using relevant OpenShift routines
3. Solvers content is respected when suggesting environment

**Comment by mayaCostantini** [comment]
/close
Closed by #2253
