### ISSUE TITLE
Create buildtime error filtering step

### ISSUE THREAD

**Issue by fridex** [thoth-station/adviser#226]
In the query where we retrieve all the transitive dependencies of a package, we use expose flag which states if the given package was installable into the given environment. This adds additional overhead to results which are serialized from graph database. Instead, we should simplify query to return just transitive dependencies (their ids respectively, as its done now due to cache), and create a single step in stack generation pipeline which would filter out packages which have buildtiem errors - the query should respect solver version and/or datetime where the software stack was resolved so that we respect changes in solver (bugfixes) and new solver updates.

**Comment by goern** [comment]
It's this still valid?
