### ISSUE TITLE
Resolver was killed as allocated memory has been exceeded (OOM) for adviser reports in stage

### ISSUE THREAD

**Issue by mayaCostantini** [thoth-station/adviser#2272]
**Describe the bug**

When querying for `adviser-220223085703-a346c6ff5c75f30` in the `advise/python/` endpoint on stage, the `"error_msg"` field in the response body specifies that: 

`"Resolver was killed as allocated memory has been exceeded (OOM) - https://thoth-station.ninja/j/oom"`

**To Reproduce**

Query for the solver document above on the `advise/python/` endpoint and see the error.

**Expected behavior**

The adviser result is returned without exceeding memory limit.

**Comment by fridex** [comment]
/lifecycle active
/assign @fridex 
/priority critical-urgent

Proposed a memory optimizer, the next step is to configure it in the deployment.

**Comment by fridex** [comment]
OOM errors are no longer present in integration-tests.

/close
