### ISSUE TITLE
BUG: Runtime environment used is no longer supported

### ISSUE THREAD

**Issue by fridex** [thoth-station/adviser#2295]
**Describe the bug**

The following `WARNING` message is printed to the terminal, but it shouldn't:

```
https://thoth-station.ninja/j/eol_env │ Runtime environment used is no longer supported, it is recommended to switch to another runtime environment │ ⚠️ WARNING  
```

**To Reproduce**
1. Ask for recommendations for UBI8 Python 3.8
2. Check the `WARNING` message produced

**Expected behavior**

This warning message should appear in logs only if the used runtime environment is not supported, meaning there is no corresponding entry in `solvers` configmap. For UBI8 Python 3.8, we should have entries in our prod deployment.

**Comment by mayaCostantini** [comment]
The solver for `ubi8` and `py38` seems to be missing from the [configmap](https://github.com/thoth-station/thoth-application/blob/46a0e22012a34eb76921a5c65e2aa45dc31e23bd/core/overlays/aws-prod/common/configmaps.yaml#L39).

**Comment by fridex** [comment]
The bug seems to be in adviser implementation where `ubi` is not considered as an alternative to `rhel` (they are binary compatible):

https://github.com/thoth-station/adviser/blob/3d7e4af9ef25afa5809574d0e0f0f51cc795d233/thoth/adviser/boots/solvers_configured.py#L72-L77

**Comment by fridex** [comment]
Actually, we consider it as an alternative based on UbiBoot that is run first. The issue here is in the operating system version string that was not normalized. #2300 should fix it.
