### ISSUE TITLE
Make sure `torch==1.11.0+cu113` gets resolved and is available in recommendations

### ISSUE THREAD

**Issue by fridex** [thoth-station/adviser#2318]
## Descriptions

See https://github.com/pypa/pipenv/issues/5022

### Additional context

We hadn't https://download.pytorch.org/whl/cu113 index registered.

## Acceptance Criteria

- make sure we have cu113 index enabled and it is monitored
- make sure we solve torch from the cu113 index
- make sure torch 11.3 is available in thoth recommendations

Note this is a CUDA 11.3 build.

**Comment by matteius** [comment]
Could you describe more details on this linked issue from pipenv? -- It would be helpful to understand more so that we can better improve how it works with regards to non-pypi public and private indexes.  Thanks!

**Comment by fridex** [comment]
We develop a public cloud Python resolver that resolves application dependencies - Thoth. Unlike Pipenv, we resolve application dependencies and provide guidance which dependencies should be installed to have secure, performant or stable application dependencies. [Here is a top-level article](https://developers.redhat.com/articles/2022/03/07/manage-python-security-thoths-cloud-based-dependency-resolver#) which links to other articles describing what we do if you are curious about the project.

We do [cross-index resolution](https://www.youtube.com/watch?v=UCt37waSa6g) for publicly available package indexes. Unfortunately, we hadn't cu113 index enabled and monitored, thus we cannot provide guidenance on consuming packages from there (hence the issue to register the pytorch index).

**Comment by fridex** [comment]
Here is [more info](https://www.youtube.com/watch?v=UCt37waSa6g&t=4403s) and [a demo](https://www.youtube.com/watch?v=UCt37waSa6g&t=1h18m48s). Project homepage is https://thoth-station.ninja

**Comment by harshad16** [comment]
We have registry the indexed and the solved for torch==1.11.0+cu113
https://stage.thoth-station.ninja/api/v1/python/package/version/environments?name=torch&version=1.11.0%2Bcu113&index=https%3A%2F%2Fdownload.pytorch.org%2Fwhl%2Fcu113

Closing this issue.
please re-open if more information is needed.
