### ISSUE TITLE
Generate compatibility matrices for Tensorflow releases

### ISSUE THREAD

**Issue by mayaCostantini** [thoth-station/adviser#2326]
## Problem statement
As a Tensorflow maintainer, I would like to be able to automatically document compatibility between a new Tensorflow version and Python interpreter versions, CUDA versions, etc.

## Proposal description
Use Thoth advise to automatically generate compatibility matrices between Tensorflow versions and their dependencies in the form of a markdown documentation based on available prescriptions.

## Acceptance Criteria
To define.

**Comment by fridex** [comment]
See https://github.com/thoth-station/prescriptions/issues/21728

**Comment by mayaCostantini** [comment]
@fridex do you want to close this issue as this seems to be a duplicate of the one you cited?

**Comment by fridex** [comment]
> @fridex do you want to close this issue as this seems to be a duplicate of the one you cited?

Yes, might be seen as a duplicate.

**Comment by mayaCostantini** [comment]
/close
Duplicate of https://github.com/thoth-station/prescriptions/issues/21728
