### ISSUE TITLE
read version from library

### ISSUE THREAD

**Issue by goern** [thoth-station/adviser#233]
https://github.com/thoth-station/adviser/blob/182326859fb657d3261a81d85f9f42bb9a68fe6e/docs/source/conf.py#L29 should read the version from https://github.com/thoth-station/adviser/blob/master/thoth/adviser/__init__.py#L5

**Comment by harshad16** [comment]
The Documentation by Sphinx could be triggered in multiple ways.
Using configuration in setup.py file or by using the configuration in conf.py file. 

I believe for our projects uses the options in the setup.py file, where version is defined using the project init. CMD: we use to trigger sphinx `python setup.py build_sphinx`.
If we want to use the conf.py file to be used for configuration for Sphinx documentation. Then CMD: we would use is `sphinx-build  <source>  <destination>`.

Just wanted to make sure I provide the above information, I will add a PR for the reading version from the project in the conf.py as well.
@goern

**Comment by fridex** [comment]
Check this documentation - http://www.sphinx-doc.org/en/master/usage/advanced/setuptools.html It should be possible to propagate version and release information (the one used in docs could be `release`) from setup.py so the current approach of `python3 setup.py build_sphinx should` pick configuration as stated in setup.py
