### ISSUE TITLE
Allow users to specify CVEs that should be ignored

### ISSUE THREAD

**Issue by fridex** [thoth-station/adviser#2342]
## Problem statement

As a user of Thoth, I would like to have an ability to specify which CVEs should be ignored during the resolution process. The reason behind this could be audit procedure that makes sure specific CVEs are considered as harmful. Eg. allow CVE-XXX in TensorFlow that is affecting security only when GCS is used.

For this, we can utilize labels that would allow users specify which CVEs should be ignored by providing a CLI option or stating labels in the .thoth.yaml configuration file.

**Comment by mayaCostantini** [comment]
Closed by https://github.com/thoth-station/adviser/pull/2348
