### ISSUE TITLE
Package prescriptions validation as pre-commit hook

### ISSUE THREAD

**Issue by VannTen** [thoth-station/adviser#2391]
## Problem statement
thoth-station/prescriptions#8

## Proposal description
Create a pre-commit hook using `validate-prescriptions` ([docs for creating hooks](https://pre-commit.com/#new-hooks))

### Alternatives
Package validate-prescriptions as a Tekton pipeline.
A pre-commit hooks is better because it reuse the existing tooling with minimal
work.

## Acceptance Criteria

- [ ] Functionnal .pre-commit-hooks.yaml for invoking `validate-prescriptions`

/sig stack-guidance
/kind feature

**Comment by goern** [comment]
Uhhh, thanks for the reping!

If it's helping wegstricht the quality, let's do it!
