### ISSUE TITLE
Compatibility with packaging>=22

### ISSUE THREAD

**Issue by VannTen** [thoth-station/adviser#2405]
Revert #2404 and replace it with a proper fix for the failing import

**Comment by codificat** [comment]
Also in the python repo: https://github.com/thoth-station/python/issues/488

**Comment by harshad16** [comment]
As pointed by @codificat 
I think we make the fix in `thoth-station/python` as it occurs from there.
Maybe move PR #2404 to `thoth-station/python` as a temporary fix, and 
let's get the proper fix implemented in meantime.

This way , it would help out in other components,as any component using thoth-station/python is facing the same issue.

**Comment by VannTen** [comment]
Hum, I add not realized at first glance that thoth/python was on of our
packages. Will put the "fix" there.
