### ISSUE TITLE
time contains string

### ISSUE THREAD

**Issue by goern** [thoth-station/adviser#597]
**Describe the bug**
the attribute time contains a string: "time.mktime"

```
  "metadata": {
    "arguments": {
      "advise": {
        "library_usage": {
          "report": {
            "time": [
              "time.mktime"
            ]
}}}}
```

**To Reproduce**
1. run an advise

**Expected behavior**
it should containe a time value

**Comment by fridex** [comment]
Does your application use `time.mktime` [1]?

[1] https://docs.python.org/3/library/time.html#time.mktime

**Comment by goern** [comment]
:)
