### ISSUE TITLE
Extras in transitive dependencies not handled properly

### ISSUE THREAD

**Issue by fridex** [thoth-station/adviser#928]
**Describe the bug**

As of now, the resolution can lead to a wrong software stack produced when a transitive dependency requires a dependency with extras. Let's suppose we use a library called "lib-a" that depends on "lib-b" with "e" extras:

requirements.txt of our application:

```
lib-a
```

Install requires of "lib-a":

```
lib-b[e]
```

When resolving our stack, the `lib-a` dependency will have dependency on `lib-b`, not on `lib-b[e]`

**To Reproduce**

I don't have any direct reproducer for this, based on the code.

**Expected behavior**

The resolution process should take into account the extras `e`.

**Comment by fridex** [comment]
We will need to also adjust/modify logic behind `get_depends_on` query.

**Comment by goern** [comment]
is this still valid?

**Comment by fridex** [comment]
Not anymore.
