### ISSUE TITLE
Standardize keys for justifications

### ISSUE THREAD

**Issue by pacospace** [thoth-station/adviser#963]
**Describe the bug**
As data scientist I want to analyze adviser justifications provided having a standardized structure for the justifications.

**To Reproduce**
Compare justifications in adviser reports

**Expected behavior**
All justifications' basic structure should be the same.

**Additional context**
See: https://github.com/thoth-station/lab/pull/202 `message unit producer` by @fridex

**Comment by goern** [comment]
is this still valid?

**Comment by fridex** [comment]
> is this still valid?

Yes, it would be good to have it.
