### ISSUE TITLE
refactor into script

### ISSUE THREAD

**Issue by goern** [thoth-station/adviser#966]
can we refactor this into a script and put it in a container?  ;) 

https://github.com/thoth-station/adviser/blob/7553e4bdd31d5d4e98a49653f7369782c290f897/workflows/templates/finished-webhook-template.yaml#L25-L95

**Comment by flowersw** [comment]
I'm not seeing this file in the repo anymore. Does this mean that this issue has been resolved? Or does this template live somewhere else now? #newbie

**Comment by saisankargochhayat** [comment]
@flowersw nice catch, yes I think this can be closed, all workflow templates have been moved into https://github.com/thoth-station/thoth-application
As far as I know, this has been moved into [workflow-helpers](https://github.com/thoth-station/workflow-helpers/blob/master/thoth/workflow_helpers/trigger_finished_webhook.py)
We can close this issue out :100: 
@goern @pacospace

**Comment by pacospace** [comment]
> @flowersw nice catch, yes I think this can be closed, all workflow templates have been moved into https://github.com/thoth-station/thoth-application
> As far as I know, this has been moved into [workflow-helpers](https://github.com/thoth-station/workflow-helpers/blob/master/thoth/workflow_helpers/trigger_finished_webhook.py)
> We can close this issue out 
> @goern @pacospace

Thanks @flowersw!! as @saisankargochhayat said we moved it to the other repo! Thanks @saisankargochhayat
